<?php
session_start();
require_once __DIR__ . '/../models/AuditModel.php';
require_once __DIR__ . '/../services/PlanEnforcementService.php';
require_once __DIR__ . '/../middleware/AuthMiddleware.php';
require_once __DIR__ . '/../middleware/AccountStatusMiddleware.php';

$auth = AuthMiddleware::requireLogin(false);
AccountStatusMiddleware::ensureActive(false);

$userId = (int) ($auth['user_id'] ?? ($_SESSION['user_id'] ?? 0));
$planType = (string) ($_SESSION['plan_type'] ?? 'free');
$planEnforcement = new PlanEnforcementService();
$access = $planEnforcement->assertFeatureAccess($userId, 'export_reports');
if (empty($access['allowed'])) {
    http_response_code(403);
    die("Access Denied. Upgrade to Pro or Agency to export reports.");
}

$id = $_GET['id'] ?? null;
if (!$id) die("Invalid Audit ID");

$auditModel = new AuditModel();
$report = $auditModel->getAuditById($id);

if (!$report) die("Audit not found");

// Ownership check
if ((int) ($report['user_id'] ?? 0) !== $userId) die("Access Denied");

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SEO Report - <?php echo htmlspecialchars($report['url']); ?></title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @media print {
            .no-print { display: none; }
            body { -webkit-print-color-adjust: exact; }
        }
    </style>
</head>
<body class="bg-white p-10 max-w-4xl mx-auto">
    
    <div class="flex justify-between items-center border-b pb-6 mb-6">
        <div>
            <h1 class="text-3xl font-bold text-gray-800">SEO Audit Report</h1>
            <p class="text-gray-500 mt-1"><?php echo htmlspecialchars($report['url']); ?></p>
        </div>
        <div class="text-right">
            <p class="text-sm text-gray-500">Generated on</p>
            <p class="font-semibold"><?php echo date('M d, Y', strtotime($report['created_at'])); ?></p>
        </div>
    </div>

    <!-- Score -->
    <div class="mb-8 text-center bg-gray-50 p-6 rounded-xl border">
        <h2 class="text-gray-600 uppercase tracking-widest text-sm font-semibold">Overall SEO Score</h2>
        <div class="text-6xl font-black text-blue-600 mt-2"><?php echo $report['seo_score']; ?>/100</div>
    </div>

    <!-- Recommendations -->
    <?php if (!empty($report['details']['recommendations'])): ?>
    <div class="mb-8">
        <h3 class="text-xl font-bold border-b pb-2 mb-4">Actionable Recommendations</h3>
        <div class="space-y-4">
            <?php foreach ($report['details']['recommendations'] as $rec): ?>
                <div class="p-4 border border-gray-200 rounded-lg">
                    <h4 class="font-bold text-gray-800 flex items-center">
                        <span class="w-2 h-2 rounded-full mr-2 <?php echo $rec['type'] === 'critical' ? 'bg-red-500' : 'bg-yellow-500'; ?>"></span>
                        <?php echo htmlspecialchars($rec['category']); ?>: <?php echo htmlspecialchars($rec['message']); ?>
                    </h4>
                    <p class="text-gray-600 mt-1 text-sm"><?php echo htmlspecialchars($rec['action']); ?></p>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <?php endif; ?>

    <!-- Technical Details -->
    <div class="grid grid-cols-2 gap-6 mb-8">
        <div class="p-4 border rounded">
            <h4 class="font-bold mb-2">Meta Tags</h4>
            <p class="text-sm"><span class="font-semibold">Title:</span> <?php echo strlen($report['details']['seo']['meta_title']); ?> chars</p>
            <p class="text-sm"><span class="font-semibold">Desc:</span> <?php echo strlen($report['details']['seo']['meta_description']); ?> chars</p>
        </div>
        <div class="p-4 border rounded">
            <h4 class="font-bold mb-2">Performance</h4>
            <p class="text-sm"><span class="font-semibold">PageSpeed:</span> <?php echo $report['pagespeed_score']; ?>/100</p>
            <p class="text-sm"><span class="font-semibold">Mobile Friendly:</span> <?php echo $report['details']['seo']['mobile'] ? 'Yes' : 'No'; ?></p>
        </div>
    </div>

    <div class="text-center text-sm text-gray-400 mt-12 border-t pt-6">
        Generated by SEO Audit SaaS Tool
    </div>

    <div class="fixed top-4 right-4 no-print">
        <button onclick="window.print()" class="bg-blue-600 text-white px-4 py-2 rounded shadow hover:bg-blue-700">Download PDF</button>
    </div>

</body>
</html>
